# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 715bbddb4e1204511e2712e788a1052080dfe39b5122cba3c98e64cd90b70b35b22b98278e0e536a0a0cceb8d7010e26a04f563034d683582cdd06c368c12414

test:
  secret_key_base: 3f1e3402153886cf4b2615b7a2647a6b26a4bfe97fea84db03b15b0a8bbcf0a39ebb0200af22f51d1cb4c9bbf642aa9045d2dca72aadd1e6c12b48ddd2717c7b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
